excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://amalex5.github.io
title: Andrew at the Recurse Center!
tagline: 
description: I'm blogging about every day I spend during the Winter 2 2016 batch at the Recurse Center!
paginate: 5
